language: go
go:
  - 1.11.x
  - master
install: go get github.com/CharLemAznable/log4go
script: go test -coverprofile=coverage.txt -covermode=atomic
after_success:
- bash <(curl -s https://codecov.io/bash)
